-- ARREGLO PARA PLAN MOTO MOBILE
-- Ejecuta TODO este archivo en Supabase > SQL Editor.
-- Corrige una tabla plan_tareas creada con la version anterior.

create table if not exists public.plan_tareas (
  id bigint generated by default as identity primary key,
  semana integer not null,
  apartado text not null,
  listo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- La version anterior podia tener "estado" pero no "listo".
alter table public.plan_tareas
  add column if not exists listo boolean default false;

-- Si existe la columna antigua "estado", conserva sus Listo/Hecho.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'plan_tareas'
      and column_name = 'estado'
  ) then
    execute $sql$
      update public.plan_tareas
      set listo = case
        when lower(coalesce(estado::text, '')) in ('listo', 'hecho', 'true') then true
        else coalesce(listo, false)
      end
    $sql$;
  end if;
end $$;

update public.plan_tareas
set listo = false
where listo is null;

alter table public.plan_tareas
  alter column listo set default false;

alter table public.plan_tareas
  alter column listo set not null;

-- Cada apartado es unico DENTRO de cada semana.
create unique index if not exists plan_tareas_semana_apartado_unique
  on public.plan_tareas (semana, apartado);

-- Solo acepta los apartados que usa la app.
alter table public.plan_tareas
  drop constraint if exists plan_tareas_apartado_check;

alter table public.plan_tareas
  add constraint plan_tareas_apartado_check
  check (apartado in (
    'licenciaPlacas',
    'motoApartado',
    'cascos',
    'gasolina',
    'saldoNovia',
    'darNovia',
    'gym',
    'ahorro',
    'amazonMusic'
  ));

create or replace function public.update_plan_moto_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_plan_tareas_updated_at on public.plan_tareas;
create trigger trg_plan_tareas_updated_at
before update on public.plan_tareas
for each row execute function public.update_plan_moto_updated_at();

alter table public.plan_tareas enable row level security;

revoke all on table public.plan_tareas from anon;
revoke all on table public.plan_tareas from authenticated;
grant select, insert, update, delete on table public.plan_tareas to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Fuerza a la API de Supabase a detectar la nueva columna.
notify pgrst, 'reload schema';
