-- PLAN MOTO MOBILE - ESQUEMA COMPLETO
-- Ejecuta este archivo en Supabase > SQL Editor para una instalacion nueva.
-- Si ya tienes las tablas, tambien funciona como migracion segura.

create table if not exists public.plan_semanal (
  id bigint generated by default as identity primary key,
  semana integer not null,
  fecha date,
  ingreso numeric(12,2) not null default 0,
  licencia_placas numeric(12,2) not null default 0,
  moto_apartado numeric(12,2) not null default 0,
  quincena_moto text,
  cascos numeric(12,2) not null default 0,
  gasolina numeric(12,2) not null default 0,
  saldo_novia numeric(12,2) not null default 0,
  dar_novia numeric(12,2) not null default 0,
  gym numeric(12,2) not null default 0,
  ahorro numeric(12,2) not null default 0,
  amazon_music numeric(12,2),
  estado text not null default 'Pendiente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.plan_semanal add column if not exists semana integer;
alter table public.plan_semanal add column if not exists fecha date;
alter table public.plan_semanal add column if not exists ingreso numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists licencia_placas numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists moto_apartado numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists quincena_moto text;
alter table public.plan_semanal add column if not exists cascos numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists gasolina numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists saldo_novia numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists dar_novia numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists gym numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists ahorro numeric(12,2) default 0;
alter table public.plan_semanal add column if not exists amazon_music numeric(12,2);
alter table public.plan_semanal add column if not exists estado text default 'Pendiente';
alter table public.plan_semanal add column if not exists created_at timestamptz default now();
alter table public.plan_semanal add column if not exists updated_at timestamptz default now();

update public.plan_semanal set estado = 'Listo' where estado = 'Hecho';
create unique index if not exists plan_semanal_semana_unique on public.plan_semanal (semana);

alter table public.plan_semanal drop constraint if exists plan_semanal_estado_check;
alter table public.plan_semanal
  add constraint plan_semanal_estado_check
  check (estado in ('Pendiente', 'Listo'));

create or replace function public.update_plan_moto_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_plan_semanal_updated_at on public.plan_semanal;
create trigger trg_plan_semanal_updated_at
before update on public.plan_semanal
for each row execute function public.update_plan_moto_updated_at();

-- Un registro independiente por apartado y por semana.
create table if not exists public.plan_tareas (
  id bigint generated by default as identity primary key,
  semana integer not null,
  apartado text not null,
  listo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibilidad con la version anterior que tenia "estado" y no "listo".
alter table public.plan_tareas
  add column if not exists listo boolean default false;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'plan_tareas'
      and column_name = 'estado'
  ) then
    execute $sql$
      update public.plan_tareas
      set listo = case
        when lower(coalesce(estado::text, '')) in ('listo', 'hecho', 'true') then true
        else coalesce(listo, false)
      end
    $sql$;
  end if;
end $$;

update public.plan_tareas set listo = false where listo is null;
alter table public.plan_tareas alter column listo set default false;
alter table public.plan_tareas alter column listo set not null;

create unique index if not exists plan_tareas_semana_apartado_unique
  on public.plan_tareas (semana, apartado);

alter table public.plan_tareas drop constraint if exists plan_tareas_apartado_check;
alter table public.plan_tareas
  add constraint plan_tareas_apartado_check
  check (apartado in (
    'licenciaPlacas',
    'motoApartado',
    'cascos',
    'gasolina',
    'saldoNovia',
    'darNovia',
    'gym',
    'ahorro',
    'amazonMusic'
  ));

drop trigger if exists trg_plan_tareas_updated_at on public.plan_tareas;
create trigger trg_plan_tareas_updated_at
before update on public.plan_tareas
for each row execute function public.update_plan_moto_updated_at();

alter table public.plan_semanal enable row level security;
alter table public.plan_tareas enable row level security;

revoke all on table public.plan_semanal from anon;
revoke all on table public.plan_semanal from authenticated;
revoke all on table public.plan_tareas from anon;
revoke all on table public.plan_tareas from authenticated;

grant select, insert, update, delete on table public.plan_semanal to service_role;
grant select, insert, update, delete on table public.plan_tareas to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
